# Generated by Django 3.0.3 on 2022-05-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_gen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPasswords',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('for_site', models.TextField()),
            ],
        ),
    ]
